version: '3.7'

services:

  scan:
    build: ./scan
    image: flavienbwk/clair-docker/quay-clair-scan:v4.3.0
    network_mode: host
    privileged: true # hate this, Docker team should make dind-rootless really rootless
    environment:
      IMAGE_NAME: node:10-alpine
      CLAIR_ENDPOINT: "http://172.17.0.1:6060"
      # Filling REGISTRY_USERNAME env variables will trigger registry authentication
      # REGISTRY_ENDPOINT must be **empty** for authenticate against Docker Hub
      REGISTRY_ENDPOINT:
      REGISTRY_USERNAME:
      REGISTRY_PASSWORD:
