name: Linux build of clair-docker

on: [push]

jobs:

  build-linux:
    name: Ubuntu 20.04 build of clair-docker scanner
    runs-on: ubuntu-20.04

    steps:

      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        id: extract_branch
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./scan
          push: false
          tags: flavienbwk/clair-docker/quay-clair-scan:v4.3.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Build and push
        id: docker_build_push
        if: ${{ env.BRANCH_NAME }} == 'master'
        uses: docker/build-push-action@v2
        with:
          context: ./scan
          push: true
          tags: flavienbwk/clair-docker/quay-clair-scan:v4.3.0
